# This workflow will install Python dependencies, run tests and lint with Python 3.8
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: CI Status

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        python-version: ["3.7", "3.8", "3.9"]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8
        pip install pytest-xvfb
        pip install -r requirements.txt
        pip install -r dev-requirements.txt
    - name: Install packages for testing a pyqt app on ubuntu
      run: |
        if [ "$RUNNER_OS" == "Linux" ]; then
          sudo apt-get install libxcb-xinerama0 pyqt5-dev-tools
        fi
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings.
        flake8 . --count --exit-zero --max-line-length=120 --statistics
    - name: Test with pytest
      run: |
        python run_tests.py
