# This workflow will install Python dependencies, run tests and lint with Python 3.8
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: CI Status

on:
  push:
    branches: [ "blah" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        python-version: [3.7, 3.8, 3.9]
        pyqt-version: ['5.12.3', '5.15.7']
    env:
      DISPLAY: ':99.0'
      QT_MAC_WANTS_LAYER: 1

    steps:
    - uses: actions/checkout@v3
    - name: Setup conda
      uses: conda-incubator/setup-miniconda@v2
      with:
        python-version: ${{ matrix.python-version }}
        mamba-version: "*"
        channels: conda-forge
        activate-environment: pydm-env
    - name: Install python packages
      shell: bash -el {0}
      run: |
        if [ "$RUNNER_OS" == "Windows" ]; then
          mamba install flake8 pyqt=${{ matrix.pyqt-version }} 
          mamba install --file requirements.txt 
          mamba install --file windows-dev-requirements.txt
        elif [ "$RUNNER_OS" == "LINUX" ]; then
          mamba install flake8 pyqt=${{ matrix.pyqt-version }} $(cat requirements.txt dev-requirements.txt)
        else
          mamba install flake8 pyqt=${{ matrix.pyqt-version }} $(cat requirements.txt dev-requirements.txt)
        fi
    - name: Install packages for testing a pyqt app on ubuntu
      shell: bash -el {0}
      run: |
        if [ "$RUNNER_OS" == "Linux" ]; then
          sudo apt install xvfb herbstluftwm libxkbcommon-x11-0 libxcb-icccm4 libxcb-image0 libxcb-keysyms1 libxcb-randr0 libxcb-render-util0 libxcb-xinerama0 libxcb-xfixes0 x11-utils 
          sudo /sbin/start-stop-daemon --start --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -screen 0 1024x768x24 -ac +extension GLX +render -noreset
          sleep 3
          sudo /sbin/start-stop-daemon --start --pidfile /tmp/custom_herbstluftwm_99.pid --make-pidfile --background --exec /usr/bin/herbstluftwm
          sleep 1
        fi
    - name: Lint with flake8
      shell: bash -el {0}
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings.
        flake8 . --count --exit-zero --max-line-length=120 --statistics
    - name: Test with pytest
      shell: bash -el {0}
      run: |
        python run_tests.py
