# This workflow will install Python dependencies, run tests and lint with Python 3.8
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: CI Status

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        python-version: ["3.7"]

    steps:
    - uses: actions/checkout@v3
    - name: Setup conda
      uses: conda-incubator/setup-miniconda@v2
      with:
        python-version: ${{ matrix.python-version }}
        mamba-version: "*"
        channels: conda-forge
        activate-environment: pydm-env
    - name: Install python packages
      shell: bash -l {0}
      run: |
        mamba install flake8 pytest-xvfb
        mamba install -r requirements.txt
        mamba install -r dev-requirements.txt
    - name: Install packages for testing a pyqt app on ubuntu
      run: |
        if [ "$RUNNER_OS" == "Linux" ]; then
          sudo apt-get install libxcb-xinerama0 pyqt5-dev-tools
        fi
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings.
        flake8 . --count --exit-zero --max-line-length=120 --statistics
    - name: Test with pytest
      run: |
        python run_tests.py
