name: Publish Documentation

on:
  push:
    branches:
      - master

jobs:
  deploy:
    if: ${{ github.repository == 'jbellister-slac/pydm' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: conda-incubator/setup-miniconda@v2
        with:
          python-version: 3.9
          mamba-version: "*"
          channels: conda-forge
          activate-environment: pydm-docs

      - name: Install python packages
        shell: bash -el {0}
        run: |
          mamba install pydm $(cat docs-requirements.txt)

      - name: Build Docs
        shell: bash -l {0}
        run: |
          pushd docs
          make html
          popd

      - name: Archive production artifacts
        uses: actions/upload-artifact@v2
        with:
          name: built-docs
          path: build/html


#      - name: Deploy to gh-pages
#        uses: peaceiris/actions-gh-pages@v3
#        with:
#          github_token: ${{ secrets.GITHUB_TOKEN }}
#          publish_dir: build/html
