# This workflow will run when a new release is published and upload it to PyPI using trusted publishing.
# For more information: https://docs.pypi.org/trusted-publishers/

name: Publish - PyPI

on:
  release:
    types:
      - published

jobs:
  build:
    name: Build new release
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install setuptools wheel

    - name: Build Package
      run: python setup.py sdist

    - name: Upload package
      uses: actions/upload-artifact@v3
      with:
        name: package
        path: dist/*

  publish:
    name: Publish release to PyPI
    runs-on: ubuntu-latest
    permissions:
      id-token: write # Used for trusted publishing
    steps:
      - name: Download package
        uses: actions/download-artifact@v3
        with:
          name: package

      - name: Publish package distributions to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          repository-url: https://test.pypi.org/legacy/
